### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by pataquets**
Add Dockerfile to enable image building.
Using the official NodeJS image, 'onbuild' tag. More info at https://hub.docker.com/_/node/

'Onbuild' image tag takes care of NodeJS standard build steps (see link). I'm not very familiar with building.

Build image from local source:

```
$ docker build -t nerdshow .
```

Run:
```
$ docker run --rm -it -p 8008:8008 nerdshow
```
You should be able to browse it at localhost:8008 .
The above image will not have any presentation, other than the ones found at the examples dir in the sources. The above command will just run the source's examples dir, which will be fine to build & test most of the time.
For convenience, there's a still quicker to test, already built image on my Docker Hub. Test it by running:
```
$ docker run --rm -it -p 8008:8008 pataquets/nerdshow [options...]
```
Using `--rm` instead of `-d` makes the container not go background and it to be deleted after stop. Should stop by `CTRL+C`'ing it, but doesn't work, even it correctly receives SIGTERM. Use ```docker stop``` from another terminal, instead. Could not found the cause, but I suspect about NodeJS being the culprit.

### Usage
Using the resulting image, you will be able to build your own Docker images based on it with any presentation baked in.
Here it is an example Dockerfile (using my public image as base to make it work). Drop it in any presentation's source directory (eg. 'examples/about'):
```
FROM pataquets/nerdshow

COPY . /presentation/

RUN bin/nerdshow-generate /presentation/presentation.json --zoom-enabled

CMD [ "/presentation/", "--debug" ]
```

Build it:
```
docker build nerdshow-test .
```
Run it:
```
docker run --rm -it -p 8008:8008 nerdshow-test
```

Optional improvement to come (maybe in another issue):
- Create an 'official', based on your repo, automated build at Docker Hub for the image: https://docs.docker.com/docker-hub/builds/ . This way people can use as base image to bake their own presentations. Just requires a free Docker Hub account and a following a quick 'Create automated build' process. I'll be happy to help on it, if needed.

### CODE REVIEW

**Comment by hgoebl** [comment]
Thanks @pataquets for your work!
I'm not yet the big Docker pro (though I'm working on it).
If you want, you could extend README.md with a description how to use nerdshow with Docker.
You can as well link to your docker image on docker Hub, if you like, because I'm afraid I cannot support the image on my own, at least currently. What do you think?

**Comment by pataquets** [comment]
@hgoebl It depends on which features and which use cases you want to support with Docker.
An 'official' Automated Build created from _your_ repo is needed if you want to support building Nerdshow images with presentations built-in. It's a one-time, easy setup process.
To get a better idea of what can be done, check what I've done with [Bedecked](https://github.com/jtrussell/bedecked) and let me know what are you interested in.
I will gladly submit a PR with docs. For the 'package your own self-contained presentation Docker image' use case, I would also add an example Dockerfile in the example presentation dir, ready to build and experiment. It would be more descriptive, since Nerdshow has the generate step.
Let me know what works for you. Of course, I'm ready if you need assistance with the process.

**Comment by pataquets** [comment]
@hgoebl : How about creating an AB discussed above? Did you checked my work with Bedecked? I would love to add it to Nerdshow, too. Ping me if you have doubts, and I'll do my best on addressing them.

**Comment by hgoebl** [comment]
Sorry, currently I don't have enough time for this project. You can fork it, do further development and provide Docker support as you like. I'll be glad to merge it or provide a link to your repo for interested guys.

**Pull request merged**
